version: '3.8'

services:
  backend:
    env_file:
      - .env
    environment:
      SERVICE_PORT: '${API_PORT}'
      SERVICE_HOST: '${API_HOST}'
    build: '.'
    volumes:
      - ./src:/usr/app/
      - /usr/app/node_modules
    command: npm start
    ports:
      - '${API_PORT}:${API_PORT}'
